# Generated by Django 5.1.2 on 2025-03-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price_per_day',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price_per_week',
        ),
        migrations.AddField(
            model_name='listing',
            name='pricing_unit',
            field=models.CharField(choices=[('hour', 'Per Hour'), ('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month'), ('year', 'Per Year')], default='day', max_length=20),
        ),
    ]
