# Generated by Django 5.1.2 on 2025-03-07 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_price_per_day_listing_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='images',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.listing'),
            preserve_default=False,
        ),
    ]
